In [1]:
import numpy as np
a = np.arange(7)
a2 = a[np.newaxis, :]
a2.shape

(1, 7)

## Numpy Arrays

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
## Transform the list array to the numpy array
np.array(mylist)

array([1, 2, 3])

In [5]:
myNumpyArr = np.array(mylist)

In [6]:
type(myNumpyArr)

numpy.ndarray

In [7]:
## Multi-dymantional array
my_metrix = [[1,2,3],[4,5,6],[7.8,9]]

In [8]:
type(my_metrix)

list

In [9]:
my_metrix

[[1, 2, 3], [4, 5, 6], [7.8, 9]]

In [10]:
np.array(my_metrix)

C:\PROGRA~1\KMSpico\temp/ipykernel_7936/1480482832.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array(my_metrix)


array([list([1, 2, 3]), list([4, 5, 6]), list([7.8, 9])], dtype=object)

In [11]:
np.arange(0,100,20)

array([ 0, 20, 40, 60, 80])

In [12]:
# creating number of columns
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
# creating number of rows and columns
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
# the alternative to implement the above twos statement
np.ones(5) 

array([1., 1., 1., 1., 1.])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
# return a list from a start number to end number with equily space.
# like if I want to print any number from 0 to 10 with the equile space of 3
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [19]:
# Random distributaion of data
np.random.rand(1)

array([0.54079726])

In [20]:
# Random distributaion of data for a metrix. concept is like number of rows and columns
np.random.rand(2,5)

array([[0.03125259, 0.54353292, 0.90599211, 0.36511521, 0.94185248],
       [0.80798039, 0.79251918, 0.75991674, 0.47790706, 0.80713261]])

In [21]:
# Data distribution followed by standared normal distributation
np.random.randn(10)

array([-0.14993555,  0.18859085, -1.54194659,  0.37054314,  0.95575573,
       -0.7495082 ,  0.64012052, -1.09941576, -0.54411231,  1.18788375])

In [22]:
np.random.randn(2,4)

array([[ 0.86324713,  1.0835253 ,  0.80129006, -1.03019561],
       [-0.08479568,  0.10465607,  0.36034914, -0.11249252]])

In [23]:
# now return the random integers
np.random.randint(10)

7

In [24]:
# now return the random integers for the number of 5 number os integers from 0 to 100
np.random.randint(0,100,5)

array([21, 35, 13, 45, 74])

In [25]:
# now return the random integers for the number of 5 number os integers from 0 to 100 where it will be arrange 4,5 array
np.random.randint(0,100,(4,5))

array([[47, 74, 90, 40, 71],
       [80, 76, 99, 35,  0],
       [43, 90, 25,  5, 25],
       [70, 54, 72,  1, 22]])

In [26]:
np.random.seed(48)
np.random.rand(4)

array([0.01749027, 0.89157327, 0.28486117, 0.29897638])

In [27]:
np.random.seed(48)
np.random.rand(4)

array([0.01749027, 0.89157327, 0.28486117, 0.29897638])

In [28]:
arr = np.arange(0, 25)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## Do some for very basic practical implementation

In [31]:
arr_list_smp = np.random.randint(0,200, 10)
arr_list_smp

array([198,  34,  92, 157,   6, 159,  46, 176,  28,  58])

In [32]:
# get the max value
arr_list_smp.max()

198

In [33]:
# get the minimum value
arr_list_smp.min()

6

In [34]:
# get the index location of max value
arr_list_smp.argmax()

0

In [35]:
# get the index location of minimum min value
arr_list_smp.argmin()

4

In [36]:
# get the data type of tha array
arr_list_smp.dtype

dtype('int32')

In [37]:
arr_list_smp

array([198,  34,  92, 157,   6, 159,  46, 176,  28,  58])

In [38]:
arr_list_smp.shape

(10,)

In [39]:
arr.shape

(25,)

In [40]:
arr_list_smp.reshape(5,2)

array([[198,  34],
       [ 92, 157],
       [  6, 159],
       [ 46, 176],
       [ 28,  58]])

## Indexing and Selection

In [41]:
arrINS = np.arange(0,11)
arrINS

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arrINS[8]

8

In [43]:
arrINS[2:6]

array([2, 3, 4, 5])

In [44]:
arrINS[:6]

array([0, 1, 2, 3, 4, 5])

In [45]:
arrINS[6:]

array([ 6,  7,  8,  9, 10])

In [46]:
# Brostcust
arrINS[0:5] = 100
arrINS

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [47]:
# array slising
slice_of_array = arrINS[6:11]
slice_of_array

array([ 6,  7,  8,  9, 10])

In [48]:
arrOpr = np.arange(0,10)
arrOpr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
arrOpr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [50]:
arrOpr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [51]:
arrOpr + arrOpr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [52]:
np.sqrt(arrOpr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [53]:
# Create an array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [54]:
# Create an array of 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [55]:
# Create an array of 10 fives
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [56]:
# Create an array of integers from 10 to 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [57]:
# Create an array of even integers from 10 to 50
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [58]:
# Create a 3x3 matrix with values range from 0 to 8
npList = np.arange(9)
npList.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [59]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [60]:
# use NumPy to generate a random number 0 to 1
np.random.rand(1)

array([0.73340264])

In [61]:
# Use NumPy to gegerate 25 random numbers sampled from a standard norman distrubation
np.random.standard_normal(25)

array([ 1.14091001, -0.73354599,  1.15896775, -0.00482197,  0.2012938 ,
        0.57141544, -2.89539019,  0.91312829, -0.95896602,  0.47101474,
       -1.42446037, -0.93946647,  1.24393149, -1.0077957 ,  0.13917656,
       -1.13865482,  0.16862671, -0.45952987, -0.94871076, -2.036109  ,
       -0.5322822 ,  0.31622074, -0.1150658 , -1.32293546, -0.25078139])

In [62]:
npMtxList = np.arange(1,101)/100
npMtxList.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [63]:
# Create an array of 20 linearly spaced points between 0 and 1:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

### NumPy Indexing and Selection

In [66]:
mat = np.arange(1,26)
mat.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [74]:
mat.sum(axis=0)

325