In [1]:
import numpy as np
a = np.arange(7)
a2 = a[np.newaxis, :]
a2.shape

(1, 7)

## Numpy Arrays

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
## Transform the list array to the numpy array
np.array(mylist)

array([1, 2, 3])

In [5]:
myNumpyArr = np.array(mylist)

In [6]:
type(myNumpyArr)

numpy.ndarray

In [7]:
## Multi-dymantional array
my_metrix = [[1,2,3],[4,5,6],[7.8,9]]

In [8]:
type(my_metrix)

list

In [9]:
my_metrix

[[1, 2, 3], [4, 5, 6], [7.8, 9]]

In [10]:
np.array(my_metrix)

C:\PROGRA~1\KMSpico\temp/ipykernel_2732/1480482832.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array(my_metrix)


array([list([1, 2, 3]), list([4, 5, 6]), list([7.8, 9])], dtype=object)

In [11]:
np.arange(0,100,20)

array([ 0, 20, 40, 60, 80])

In [12]:
# creating number of columns
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
# creating number of rows and columns
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
# the alternative to implement the above twos statement
np.ones(5) 

array([1., 1., 1., 1., 1.])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
# return a list from a start number to end number with equily space.
# like if I want to print any number from 0 to 10 with the equile space of 3
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [19]:
# Random distributaion of data
np.random.rand(1)

array([0.89407766])

In [20]:
# Random distributaion of data for a metrix. concept is like number of rows and columns
np.random.rand(2,5)

array([[0.58828724, 0.80858915, 0.03858685, 0.4319254 , 0.39522641],
       [0.79601996, 0.31206894, 0.64893342, 0.49387271, 0.2648817 ]])

In [21]:
# Data distribution followed by standared normal distributation
np.random.randn(10)

array([ 0.77718022,  0.68804234,  0.90189817,  0.56314294,  0.15070457,
        0.57014098, -0.79601077,  1.99348668,  0.12078182, -0.04182027])

In [22]:
np.random.randn(2,4)

array([[-0.2117234 ,  1.22267289, -0.66585736,  0.06410038],
       [-1.23070852,  0.47122321, -1.42831129,  0.30462333]])

In [23]:
# now return the random integers
np.random.randint(10)

1

In [24]:
# now return the random integers for the number of 5 number os integers from 0 to 100
np.random.randint(0,100,5)

array([ 8, 80, 81, 93, 67])

In [25]:
# now return the random integers for the number of 5 number os integers from 0 to 100 where it will be arrange 4,5 array
np.random.randint(0,100,(4,5))

array([[96, 45, 25, 69, 70],
       [28, 22, 30, 70, 40],
       [35,  1, 65, 48, 17],
       [26, 92,  0,  7, 41]])

In [26]:
np.random.seed(48)
np.random.rand(4)

array([0.01749027, 0.89157327, 0.28486117, 0.29897638])

In [27]:
np.random.seed(48)
np.random.rand(4)

array([0.01749027, 0.89157327, 0.28486117, 0.29897638])

In [28]:
arr = np.arange(0, 25)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## Do some for very basic practical implementation

In [34]:
arr_list_smp = np.random.randint(0,200, 10)
arr_list_smp

array([104, 143,  30,  66,  18, 181,  18,  21,  25,  92])

In [35]:
# get the max value
arr_list_smp.max()

181

In [36]:
# get the minimum value
arr_list_smp.min()

18

In [37]:
# get the index location of max value
arr_list_smp.argmax()

5

In [38]:
# get the index location of minimum min value
arr_list_smp.argmin()

4

In [40]:
# get the data type of tha array
arr_list_smp.dtype

dtype('int32')

In [41]:
arr_list_smp

array([104, 143,  30,  66,  18, 181,  18,  21,  25,  92])

In [42]:
arr_list_smp.shape

(10,)

In [47]:
arr.shape

(25,)

In [48]:
arr_list_smp.reshape(5,2)

array([[104, 143],
       [ 30,  66],
       [ 18, 181],
       [ 18,  21],
       [ 25,  92]])

## Indexing and Selection

In [52]:
arrINS = np.arange(0,11)
arrINS

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arrINS[8]

8

In [54]:
arrINS[2:6]

array([2, 3, 4, 5])

In [56]:
arrINS[:6]

array([0, 1, 2, 3, 4, 5])

In [58]:
arrINS[6:]

array([ 6,  7,  8,  9, 10])

In [62]:
# Brostcust
arrINS[0:5] = 100
arrINS

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [63]:
# array slising
slice_of_array = arrINS[6:11]
slice_of_array

array([ 6,  7,  8,  9, 10])